Calm0815/image filter library
Nishida-Lab/phoxi_ros_pkg pull request #19
Opened 2019-11-05 14:22 UTC by calm0815

https://github.com/Nishida-Lab/phoxi_ros_pkg/issues/18#issue-517708927 の指摘を受けて修正しました。
事前確認不足でしたすいません。

ciが通過するのは確認しました。

2019-11-05 16:25 UTC, MoriKen254 requested changes
お疲れさまです！
まず、実行モジュール名に `_node` をつけるのは賛成なので、そのまま継続下さい。

その上で、下記の`LIBRARIES ${PROJECT_NAME}`が不要かなと思います。

```
catkin_package(
  INCLUDE_DIRS
  LIBRARIES ${PROJECT_NAME} <- これね
  CATKIN_DEPENDS
    cv_bridge
    image_transport
    roscpp
)
```

なぜなら、大本のGitLabCIで、下記のエラーが出力されているためです。

```
phoxi_img_converter: CMakeLists.txt(14): error: exported library 'phoxi_img_converter' is not a library
     * You listed a library in the LIBRARIES stanza of your
     * catkin_package() call, but it really is an executable.
```

確かに、実行モジュール名に `_node` を付与することでライブラリ名との競合は回避できましたが、エラーの本質は「そもそもこのパッケージはライブラリではない」ことに起因するので、そこを解決するのが本筋かな、と思います。

よろしくお願いします！＼(^o^)／

2019-11-06 11:12 UTC, calm0815 commented
ci通過しました

2019-11-06 12:16 UTC, MoriKen254 approved these changes
いいですね！お疲れ様でした！

Approve!

2019-11-06 13:17 UTC, calm0815 commented
ありがとうございました！
マージします。

2019-11-06 13:17 UTC, merged