Calm0815/refactoring
Nishida-Lab/phoxi_ros_pkg pull request #9
Opened 2019-10-30 14:36 UTC by calm0815

機能ごとにクラス化するなどのリファクタをしました。
自分の環境での動作確認はできています。

指摘などあればおねがいします

2019-10-30 16:56 UTC, MoriKen254 requested changes
お疲れ様です！

一回これで回しましょう！

2019-10-30 16:56 UTC, MoriKen254 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
>  #include <sensor_msgs/image_encodings.h>
インクルードガードを入れてください

2019-10-30 16:56 UTC, MoriKen254 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
>  #include <sensor_msgs/image_encodings.h>
あれ、入ってますね。失礼しました。例によって劣悪ネット環境で読み込み遅れたかもですね。

ジョイフルの微妙なwifi方がまだ速い笑。

2019-10-30 16:56 UTC, MoriKen254 commented on phoxi_img_converter/src/convert_pub.cpp
> +void ConvertPub::scaling(cv_bridge::CvImagePtr original_img, cv_bridge::CvImagePtr rescaled_img)
細かいですが、メソッド名は動詞の方がいいです。

また、可能であれば目的語も付けて、よりメソッドの役割を明確に表した方が良いです。

2019-10-30 16:56 UTC, MoriKen254 commented on phoxi_img_converter/src/convert_pub.cpp
> +void ConvertPub::filtering(void)
こちらも動詞の方がベター

2019-10-30 16:56 UTC, MoriKen254 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
> +#include <opencv2/highgui.hpp>
opencv周りはcppにインクルードすれば良さげ。

2019-10-30 16:56 UTC, MoriKen254 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
> +#endif
インクルードガードコメント

2019-10-30 16:56 UTC, MoriKen254 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
> +#include <iostream>
iostreamもcppでインクルード

2019-10-31 03:19 UTC, calm0815 commented on phoxi_img_converter/src/convert_pub.cpp
> +void ConvertPub::scaling(cv_bridge::CvImagePtr original_img, cv_bridge::CvImagePtr rescaled_img)
「scalePixVal」に変更しました

2019-10-31 03:20 UTC, calm0815 commented on phoxi_img_converter/src/convert_pub.cpp
> +void ConvertPub::filtering(void)
「filterImg」に変更しました

2019-10-31 03:42 UTC, calm0815 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
> +#endif
追加しました
> https://github.com/Nishida-Lab/phoxi_ros_pkg/pull/9/commits/399877d59ee12ee58f1d5226a40684c34b5a6f30

2019-10-31 03:43 UTC, calm0815 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
> +#include <opencv2/highgui.hpp>
移動しました
> https://github.com/Nishida-Lab/phoxi_ros_pkg/pull/9/commits/49452d24584aaf417dc9cd58299a5909a9b042fd

2019-10-31 03:43 UTC, calm0815 commented on phoxi_img_converter/include/phoxi_img_converter/convert_pub.h
> +#include <iostream>
移動しました
> https://github.com/Nishida-Lab/phoxi_ros_pkg/pull/9/commits/49452d24584aaf417dc9cd58299a5909a9b042fd

2019-10-31 03:45 UTC, qoopen0815 reviewed
ついでにROS_INFOも付け加えました。
以下のようになります。

```
( ^q^) < norepo )
kuwano@pc0815: ~/denso_ws
>> roslaunch phoxi_bringup phoxi_bringup.launch 
... logging to /home/kuwano/.ros/log/7ec0063a-fb8f-11e9-bca0-38d5471a4700/roslaunch-pc0815-20483.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://pc0815:43729/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    convert_pub (phoxi_img_converter/convert_pub)
    info_pub (phoxi_camera_info_pub/info_pub)

ROS_MASTER_URI=http://localhost:11311

process[info_pub-1]: started with pid [20609]
process[convert_pub-2]: started with pid [20622]
[ INFO] [1572493254.918598199]: waiting image ...
[ INFO] [1572493255.334672130]: subscribed !
[ INFO] [1572493255.453163838]: filtering image ...
[ INFO] [1572493255.457700977]: filtering FINISHED
[ INFO] [1572493255.465626113]: publishing image ...
```

2019-10-31 12:11 UTC, MoriKen254 commented
いいですね！

ちなみに、ONCE付きのROS_INFOというのは、何回も該当する関数をcallしても、出力されるのは一回だけ、という仕様ですか？

2019-10-31 13:53 UTC, calm0815 commented
> ちなみに、ONCE付きのROS_INFOというのは、何回も該当する関数をcallしても、出力されるのは一回だけ、という仕様ですか？

[ここ](http://forestofazumino.web.fc2.com/ros/ros_log_macro.html)によると、その仕様の様です。何度もログが来ないので最適かと思い、試してみました

2019-10-31 14:33 UTC, MoriKen254 approved these changes
ログについても、了解です！これで行きましょう！
最後に他環境検証ができたら、マージして下さい。

Approve!

2019-10-31 14:37 UTC, calm0815 commented
既に @MamiInoue さんの環境で動作確認してますのでマージします。
レビューありがとうございました😊

2019-10-31 14:37 UTC, merged

2019-11-01 11:28 UTC, MoriKen254 commented
お疲れさまでした！